<?php
defined('_JEXEC') or die;
use Joomla\CMS\HTML\HTMLHelper;use Joomla\CMS\Router\Route;use Joomla\CMS\Session\Session;
?>
<nav class="nav nav-tabs mb-4"><a class="nav-link" href="<?php echo Route::_('index.php?option=com_academy&view=autopost&provider=facebook'); ?>">Facebook</a><a class="nav-link" href="<?php echo Route::_('index.php?option=com_academy&view=autopost&provider=twitter'); ?>">X / Twitter</a><a class="nav-link" href="<?php echo Route::_('index.php?option=com_academy&view=autopost&provider=linkedin'); ?>">LinkedIn</a><a class="nav-link active" href="#">Logs</a></nav>
<div class="d-flex justify-content-between align-items-center mb-3"><p class="mb-0">Every successful and failed autopost attempt is recorded.</p><a class="btn btn-danger" href="<?php echo Route::_('index.php?option=com_academy&task=autopost.purge&'.Session::getFormToken().'=1'); ?>" onclick="return confirm('Purge all autopost logs?')">Purge Logs</a></div>
<div class="table-responsive"><table class="table"><thead><tr><th>Date</th><th>Post</th><th>Network</th><th>Event</th><th>Status</th><th>Remote ID</th><th>Details</th></tr></thead><tbody>
<?php foreach($this->items as $item): ?><tr><td><?php echo htmlspecialchars($item->created); ?></td><td><?php echo htmlspecialchars($item->title?:('#'.$item->post_id)); ?></td><td><?php echo ucfirst($item->provider); ?></td><td><?php echo ucfirst($item->event); ?></td><td><span class="badge bg-<?php echo $item->status==='success'?'success':'danger'; ?>"><?php echo ucfirst($item->status); ?></span></td><td><?php echo htmlspecialchars($item->remote_id); ?></td><td><details><summary>View</summary><div class="small mt-2"><strong>Message</strong><pre class="text-wrap"><?php echo htmlspecialchars($item->message); ?></pre><strong>Response</strong><pre class="text-wrap"><?php echo htmlspecialchars($item->response); ?></pre></div></details></td></tr><?php endforeach; ?>
<?php if(!$this->items): ?><tr><td colspan="7" class="text-center text-muted py-5">No autopost logs yet.</td></tr><?php endif; ?></tbody></table></div>
