<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_academy
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\FileLayout;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Academy\Administrator\Extension\AcademyComponent;
use Joomla\Component\Academy\Site\Helper\RouteHelper;

/** @var \Joomla\Component\Academy\Site\View\Post\HtmlView $this */
// Create shortcuts to some parameters.
$params  = $this->item->params;
Factory::getApplication()->getDocument()->getWebAssetManager()
    ->useStyle('fontawesome')
    ->registerAndUseStyle('com_academy.post-detail', 'com_academy/post-detail.css', ['version' => 'auto'])
    ->registerAndUseScript('com_academy.post-print', 'com_academy/post-print.js', ['version' => 'auto'], ['defer' => true]);
$canEdit = $params->get('access-edit');
$user    = $this->getCurrentUser();
$htag    = $this->params->get('show_page_heading') ? 'h2' : 'h1';

// Check if associations are implemented. If they are, define the parameter.
$assocParam        = (Associations::isEnabled() && $params->get('show_associations'));
$currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;
?>
<?php echo LayoutHelper::render('postnav', ['params' => $this->item->params], JPATH_COMPONENT . '/layouts'); ?>
<div class="com-content-post genesis-print-article item-page<?php echo $this->pageclass_sfx; ?>">
    <meta itemprop="inLanguage" content="<?php echo ($this->item->language === '*') ? Factory::getApplication()->get('language') : $this->item->language; ?>">
    <?php if ($this->params->get('show_page_heading')) : ?>
    <div class="page-header">
        <h1> <?php echo $this->escape($this->params->get('page_heading')); ?> </h1>
    </div>
    <?php endif;
if (!empty($this->item->pagination) && !$this->item->paginationposition && $this->item->paginationrelative) {
    echo $this->item->pagination;
}
?>

    <?php $useDefList = $params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
|| $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam; ?>

    <div class="post-print-toolbar d-flex flex-wrap align-items-baseline gap-3 mb-3">
        <button type="button" class="post-print-button" data-post-print><span class="fa-solid fa-print me-2" aria-hidden="true"></span>Print</button>
        <div class="post-details-row text-muted small ms-auto">
        <?php if ($params->get('show_create_date')) : ?><span>Created: <?php echo HTMLHelper::_('date', $this->item->created, 'DATE_FORMAT_LC3'); ?></span><?php endif; ?>
        <?php if ($params->get('show_modify_date') && !empty($this->item->modified)) : ?><span>Last Updated: <?php echo HTMLHelper::_('date', $this->item->modified, 'DATE_FORMAT_LC3'); ?></span><?php endif; ?>
        </div>
    </div>
    <?php if ($params->get('show_title')) : ?>
    <div class="page-header">
        <<?php echo $htag; ?>>
            <?php echo $this->escape($this->item->title); ?>
        </<?php echo $htag; ?>>
        <?php if ($this->item->state == AcademyComponent::CONDITION_UNPUBLISHED) : ?>
            <span class="badge bg-warning text-light"><?php echo Text::_('JUNPUBLISHED'); ?></span>
        <?php endif; ?>
        <?php if ($isNotPublishedYet) : ?>
            <span class="badge bg-warning text-light"><?php echo Text::_('JNOTPUBLISHEDYET'); ?></span>
        <?php endif; ?>
        <?php if ($isExpired) : ?>
            <span class="badge bg-warning text-light"><?php echo Text::_('JEXPIRED'); ?></span>
        <?php endif; ?>
    </div>
    <?php endif; ?>
    <?php if ($canEdit) : ?>
        <?php echo LayoutHelper::render('academy.content.icons', ['params' => $params, 'item' => $this->item], JPATH_COMPONENT . '/layouts'); ?>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentAfterTitle"?>
    <?php echo $this->item->event->afterDisplayTitle; ?>

    <?php if ($useDefList) : ?>
        <?php echo LayoutHelper::render('post-details', ['item' => $this->item, 'params' => $params, 'position' => 'above'], JPATH_COMPONENT . '/layouts'); ?>
    <?php endif; ?>

    <?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
        <?php $this->item->tagLayout = new FileLayout('posttags', JPATH_COMPONENT . '/layouts'); ?>

        <?php echo $this->item->tagLayout->render($this->item->tags->itemTags); ?>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
    <?php echo $this->item->event->beforeDisplayContent; ?>
<?php if ($params->get('access-view')) : ?>
<?php
        if (!empty($this->item->pagination) && !$this->item->paginationposition && !$this->item->paginationrelative) :
            echo $this->item->pagination;
        endif;
        ?>
        <?php if (isset($this->item->toc)) :
            echo $this->item->toc;
        endif; ?>
    <div class="com-content-post__body">
        <?php echo $this->item->text; ?>
    </div>

        <?php
        if (!empty($this->item->pagination) && $this->item->paginationposition && !$this->item->paginationrelative) :
            echo $this->item->pagination;
            ?>
        <?php endif; ?>
<?php // Optional teaser excerpt for guests?>
    <?php elseif ($params->get('show_noauth') && $user->guest) : ?>
        <?php echo LayoutHelper::render('academy.content.featured_image', $this->item, JPATH_COMPONENT . '/layouts'); ?>
        <?php echo HTMLHelper::_('content.prepare', $this->item->summary); ?>
        <?php // Optional link to let them register to see the whole post.?>
        <?php if ($params->get('show_readmore') && $this->item->body != null) : ?>
            <?php $menu = Factory::getApplication()->getMenu(); ?>
            <?php $active = $menu->getActive(); ?>
            <?php $itemId = $active->id; ?>
            <?php $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false)); ?>
            <?php $link->setVar('return', base64_encode(RouteHelper::getPostRoute($this->item->slug, $this->item->catid, $this->item->language))); ?>
            <?php echo LayoutHelper::render('academy.content.readmore', ['item' => $this->item, 'params' => $params, 'link' => $link]); ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php
    if (!empty($this->item->pagination) && $this->item->paginationposition && $this->item->paginationrelative) :
        echo $this->item->pagination;
        ?>
    <?php endif; ?>
    <?php // Content is generated by content plugin event "onContentAfterDisplay"?>
    <?php echo $this->item->event->afterDisplayContent; ?>
    <?php echo LayoutHelper::render('engagement', $this->item, JPATH_COMPONENT . '/layouts'); ?>
    <?php echo LayoutHelper::render('author-about', $this->item, JPATH_COMPONENT . '/layouts'); ?>
    <?php echo LayoutHelper::render('comments', $this->item, JPATH_COMPONENT . '/layouts'); ?>
</div>
