<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_academy
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Academy\Administrator\Extension\AcademyComponent;
use Joomla\Component\Academy\Site\Helper\RouteHelper;

/** @var \Joomla\Component\Academy\Site\View\Featured\HtmlView $this */
// Create a shortcut for params.
$params  = &$this->item->params;
$listStyle = $params->get('list_item_style', 'standard');
$canEdit = $this->item->params->get('access-edit');

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (Associations::isEnabled() && $params->get('show_associations'));

$currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
$isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isUnpublished     = $this->item->state == AcademyComponent::CONDITION_UNPUBLISHED || $isNotPublishedYet || $isExpired;
?>

<?php
$itemClasses = match ($listStyle) {
    'card', 'learning' => 'card h-100 overflow-hidden',
    'simple' => 'border-bottom py-3',
    'nickel' => 'border-start border-4 border-secondary p-3 bg-body-tertiary',
    default => '',
};
?>
<div class="<?php echo $itemClasses; ?>">
<?php
$featuredImages = json_decode((string) ($this->item->media ?? '{}'));
if (in_array($listStyle, ['card', 'learning'], true) && empty($featuredImages->featured_image)) {
    echo LayoutHelper::render('postlist.card.placeholder', $this->item, JPATH_COMPONENT . '/layouts');
} else {
    echo LayoutHelper::render('academy.content.featured_image', $this->item, JPATH_COMPONENT . '/layouts');
}
?>

<?php if ($listStyle === 'learning') : ?>
<div class="item-content learning-item-content card-body">
    <?php echo LayoutHelper::render('academy.content.blog_style_default_item_title', $this->item, JPATH_COMPONENT . '/layouts'); ?>
    <?php echo LayoutHelper::render('postlist.learning.details', $this->item, JPATH_COMPONENT . '/layouts'); ?>
</div>
<?php else : ?>

<div class="item-content <?php echo $listStyle === 'card' ? 'card-body d-flex flex-column' : ''; ?>">
    <?php if ($isUnpublished) : ?>
        <div class="system-unpublished">
    <?php endif; ?>

    <?php if ($params->get('show_title', 1)) : ?>
        <h2 class="item-title d-flex align-items-center gap-2"><?php if (!in_array($listStyle, ['card', 'learning'], true)) {
            echo LayoutHelper::render('postlist.' . $listStyle . '.avatar', $this->item, JPATH_COMPONENT . '/layouts');
        } ?><span>
        <?php if ($params->get('link_titles', 1) && $params->get('access-view')) : ?>
            <a href="<?php echo Route::_(RouteHelper::getPostRoute($this->item->slug, $this->item->catid, $this->item->language)); ?>">
                <?php echo $this->escape($this->item->title); ?>
            </a>
        <?php else : ?>
            <?php echo $this->escape($this->item->title); ?>
        <?php endif; ?>
        </span></h2>
    <?php endif; ?>

    <?php if ($this->item->state == AcademyComponent::CONDITION_UNPUBLISHED) : ?>
        <span class="badge bg-warning text-light"><?php echo Text::_('JUNPUBLISHED'); ?></span>
    <?php endif; ?>
    <?php if ($isNotPublishedYet) : ?>
        <span class="badge bg-warning text-light"><?php echo Text::_('JNOTPUBLISHEDYET'); ?></span>
    <?php endif; ?>
    <?php if ($isExpired) : ?>
        <span class="badge bg-warning text-light"><?php echo Text::_('JEXPIRED'); ?></span>
    <?php endif; ?>

    <?php if ($canEdit) : ?>
        <?php echo LayoutHelper::render('academy.content.icons', ['params' => $params, 'item' => $this->item], JPATH_COMPONENT . '/layouts'); ?>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentAfterTitle"?>
    <?php echo $this->item->event->afterDisplayTitle; ?>

    <?php // @todo Not that elegant would be nice to group the params?>
    <?php $useDefList = ($params->get('show_modify_date') || $params->get('show_publish_date') || $params->get('show_create_date')
        || $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam); ?>

    <?php if ($useDefList) : ?>
        <?php echo LayoutHelper::render('academy.content.info_block', ['item' => $this->item, 'params' => $params, 'position' => 'above'], JPATH_COMPONENT . '/layouts'); ?>
    <?php endif; ?>
    <?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
        <?php echo LayoutHelper::render('posttags', $this->item->tags->itemTags, JPATH_COMPONENT . '/layouts'); ?>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
    <?php echo $this->item->event->beforeDisplayContent; ?>

    <?php echo $this->item->summary; ?>

    <?php if ($params->get('show_readmore') && $this->item->readmore) :
        if ($params->get('access-view')) :
            $link = Route::_(RouteHelper::getPostRoute($this->item->slug, $this->item->catid, $this->item->language));
        else :
            $menu = Factory::getApplication()->getMenu();
            $active = $menu->getActive();
            $itemId = $active->id;
            $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
            $link->setVar('return', base64_encode(RouteHelper::getPostRoute($this->item->slug, $this->item->catid, $this->item->language)));
        endif; ?>

        <?php echo LayoutHelper::render('academy.content.readmore', ['item' => $this->item, 'params' => $params, 'link' => $link]); ?>

    <?php endif; ?>

    <?php echo LayoutHelper::render('postlist.' . $listStyle . '.meta', $this->item, JPATH_COMPONENT . '/layouts'); ?>
    <?php if ($listStyle === 'card') {
        echo LayoutHelper::render('postlist.card.footer', $this->item, JPATH_COMPONENT . '/layouts');
    } ?>

    <?php if ($isUnpublished) : ?>
        </div>
    <?php endif; ?>

</div>

<?php // Content is generated by content plugin event "onContentAfterDisplay"?>
<?php echo $this->item->event->afterDisplayContent; ?>
<?php endif; ?>

</div>
