<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_academy
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Academy\Administrator\Extension\AcademyComponent;
use Joomla\Component\Academy\Site\Helper\RouteHelper;

/** @var \Joomla\Component\Academy\Site\View\Category\HtmlView $this */
// Create a shortcut for params.
$params = $this->item->params;
$listStyle = $params->get('list_item_style', 'standard');
$canEdit = $this->item->params->get('access-edit');

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (Associations::isEnabled() && $params->get('show_associations'));

$currentDate   = Factory::getDate()->format('Y-m-d H:i:s');
$isUnpublished = ($this->item->state == AcademyComponent::CONDITION_UNPUBLISHED || $this->item->publish_up > $currentDate)
    || ($this->item->publish_down < $currentDate && $this->item->publish_down !== null);

?>

<?php
$itemClasses = match ($listStyle) {
    'card', 'learning' => 'card h-100 overflow-hidden',
    'simple', 'standard' => 'h-100 d-flex flex-column',
    'nickel' => 'card h-100 overflow-hidden',
    default => '',
};
?>
<div class="<?php echo $itemClasses; ?>">
<?php
$featuredImages = json_decode((string) ($this->item->media ?? '{}'));
if (in_array($listStyle, ['card', 'learning'], true) && empty($featuredImages->featured_image) && empty($this->item->category_default_image)) {
    echo $this->loadTemplate('placeholder');
} elseif (!in_array($listStyle, ['simple', 'standard', 'nickel'], true)) {
    echo $this->loadTemplate('image');
}
?>

<?php if ($listStyle === 'learning') : ?>
<div class="item-content learning-item-content card-body d-flex flex-column">
    <?php echo $this->loadTemplate('title'); ?>
    <?php echo $this->loadTemplate('footer'); ?>
</div>
<?php else : ?>

<div class="item-content <?php echo in_array($listStyle, ['card', 'nickel'], true) ? 'card-body d-flex flex-column' : (in_array($listStyle, ['simple', 'standard'], true) ? 'd-flex flex-column flex-grow-1' : ''); ?>">
    <?php if ($isUnpublished) : ?>
        <div class="system-unpublished">
    <?php endif; ?>

    <?php if (in_array($listStyle, ['simple', 'standard'], true)) : ?>
        <?php echo $this->loadTemplate('header'); ?>
    <?php else : ?>
    <?php echo $this->loadTemplate('title'); ?>
    <?php endif; ?>

    <?php if ($canEdit) : ?>
        <?php echo LayoutHelper::render('academy.content.icons', ['params' => $params, 'item' => $this->item], JPATH_COMPONENT . '/layouts'); ?>
    <?php endif; ?>

    <?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
        <?php echo $this->loadTemplate('tags'); ?>
    <?php elseif (in_array($listStyle, ['card', 'nickel'], true) && $params->get('show_tags', 1)) : ?>
        <ul class="tags list-inline invisible" aria-hidden="true"><li class="list-inline-item"><span class="btn btn-sm btn-info">&nbsp;</span></li></ul>
    <?php endif; ?>

    <?php if (!$params->get('show_intro')) : ?>
        <?php // Content is generated by content plugin event "onContentAfterTitle"?>
        <?php echo $this->item->event->afterDisplayTitle; ?>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
    <?php echo $this->item->event->beforeDisplayContent; ?>

    <?php echo $this->item->summary; ?>

    <?php if ($params->get('show_readmore') && $this->item->readmore) :
        if ($params->get('access-view')) :
            $link = Route::_(RouteHelper::getPostRoute($this->item->slug, $this->item->catid, $this->item->language));
        else :
            $menu = Factory::getApplication()->getMenu();
            $active = $menu->getActive();
            $itemId = $active->id;
            $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
            $link->setVar('return', base64_encode(RouteHelper::getPostRoute($this->item->slug, $this->item->catid, $this->item->language)));
        endif; ?>

        <?php echo LayoutHelper::render('academy.content.readmore', ['item' => $this->item, 'params' => $params, 'link' => $link]); ?>

    <?php endif; ?>

    <?php if (in_array($listStyle, ['card', 'simple', 'standard', 'nickel'], true)) : ?><div class="mt-auto pt-2"><?php endif; ?>
    <?php if ($listStyle === 'simple') : ?>
        <?php if (\Joomla\Component\Academy\Site\Helper\DateHelper::value($this->item, $params)) : ?>
            <div class="small text-muted"><span class="fa-solid fa-calendar me-1" aria-hidden="true"></span><?php echo \Joomla\Component\Academy\Site\Helper\DateHelper::render($this->item, $params); ?></div>
        <?php endif; ?>
    <?php else : ?>
    <?php echo $this->loadTemplate('meta'); ?>
    <?php endif; ?>
    <?php if (in_array($listStyle, ['card', 'nickel'], true)) {
        echo $this->loadTemplate('footer');
    } ?>
    <?php if (in_array($listStyle, ['card', 'simple', 'standard', 'nickel'], true)) : ?></div><?php endif; ?>

    <?php if ($isUnpublished) : ?>
        </div>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentAfterDisplay"?>
    <?php echo $this->item->event->afterDisplayContent; ?>
</div>
<?php endif; ?>

</div>
