<?php

/**
 * @package     Joomla.Site
 * @subpackage  com_codex
 *
 * @copyright   (C) 2006 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Language\Associations;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Layout\LayoutHelper;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Codex\Administrator\Extension\CodexComponent;
use Joomla\Component\Codex\Site\Helper\RouteHelper;

/** @var \Joomla\Component\Codex\Site\View\Featured\HtmlView $this */
// Create a shortcut for params.
$params  = &$this->item->params;
$listStyle = $params->get('list_item_style', 'standard');
$canEdit = $this->item->params->get('access-edit');

// Check if associations are implemented. If they are, define the parameter.
$assocParam = (Associations::isEnabled() && $params->get('show_associations'));

$currentDate       = Factory::getDate()->format('Y-m-d H:i:s');
$isExpired         = !is_null($this->item->publish_down) && $this->item->publish_down < $currentDate;
$isNotPublishedYet = $this->item->publish_up > $currentDate;
$isUnpublished     = $this->item->state == CodexComponent::CONDITION_UNPUBLISHED || $isNotPublishedYet || $isExpired;
?>

<?php
$itemClasses = match ($listStyle) {
    'card', 'learning' => 'card h-100 overflow-hidden',
    'simple', 'standard' => 'h-100 d-flex flex-column',
    'nickel' => 'card h-100 overflow-hidden',
    default => '',
};
?>
<div class="<?php echo $itemClasses; ?>">
<?php if ($listStyle === 'nickel') { echo LayoutHelper::render('post.nickel-header', $this->item, JPATH_COMPONENT . '/layouts'); } ?>
<?php
$featuredImages = json_decode((string) ($this->item->media ?? '{}'));
if (in_array($listStyle, ['card', 'learning'], true) && empty($featuredImages->featured_image)) {
    echo LayoutHelper::render('post.image-placeholder', $this->item, JPATH_COMPONENT . '/layouts');
} elseif (!in_array($listStyle, ['simple', 'standard', 'nickel'], true)) {
    echo LayoutHelper::render('codex.content.featured_image', $this->item, JPATH_COMPONENT . '/layouts');
}
?>

<?php if ($listStyle === 'learning') : ?>
<div class="item-content learning-item-content card-body d-flex flex-column">
    <?php echo LayoutHelper::render('codex.content.blog_style_default_item_title', $this->item, JPATH_COMPONENT . '/layouts'); ?>
    <?php echo LayoutHelper::render('post.card-footer', $this->item, JPATH_COMPONENT . '/layouts'); ?>
</div>
<?php else : ?>

<div class="item-content <?php echo in_array($listStyle, ['card', 'nickel'], true) ? 'card-body d-flex flex-column' : (in_array($listStyle, ['simple', 'standard'], true) ? 'd-flex flex-column flex-grow-1' : ''); ?>">
    <?php if ($isUnpublished) : ?>
        <div class="system-unpublished">
    <?php endif; ?>

    <?php if (in_array($listStyle, ['simple', 'standard'], true)) : ?>
        <?php echo LayoutHelper::render('post.' . $listStyle . '-header', $this->item, JPATH_COMPONENT . '/layouts'); ?>
    <?php else : ?>
    <?php if ($params->get('show_title', 1)) : ?>
        <h2 class="item-title d-flex align-items-center gap-2"><?php if (in_array($listStyle, ['standard'], true)) {
            echo LayoutHelper::render('post.avatar', $this->item, JPATH_COMPONENT . '/layouts');
        } ?><span>
        <?php if ($params->get('link_titles', 1) && $params->get('access-view')) : ?>
            <a href="<?php echo Route::_(RouteHelper::getPostRoute($this->item->slug, $this->item->catid, $this->item->language)); ?>">
                <?php echo $this->escape($this->item->title); ?>
            </a>
        <?php else : ?>
            <?php echo $this->escape($this->item->title); ?>
        <?php endif; ?>
        </span></h2>
    <?php endif; ?>

    <?php endif; ?>

    <?php if ($this->item->state == CodexComponent::CONDITION_UNPUBLISHED) : ?>
        <span class="badge bg-warning text-light"><?php echo Text::_('JUNPUBLISHED'); ?></span>
    <?php endif; ?>
    <?php if ($isNotPublishedYet) : ?>
        <span class="badge bg-warning text-light"><?php echo Text::_('JNOTPUBLISHEDYET'); ?></span>
    <?php endif; ?>
    <?php if ($isExpired) : ?>
        <span class="badge bg-warning text-light"><?php echo Text::_('JEXPIRED'); ?></span>
    <?php endif; ?>

    <?php if ($listStyle === 'nickel') { echo LayoutHelper::render('post.nickel-category', $this->item, JPATH_COMPONENT . '/layouts'); } ?>
    <?php if ($canEdit) : ?>
        <?php echo LayoutHelper::render('codex.content.icons', ['params' => $params, 'item' => $this->item], JPATH_COMPONENT . '/layouts'); ?>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentAfterTitle"?>
    <?php echo $this->item->event->afterDisplayTitle; ?>

    <?php // @todo Not that elegant would be nice to group the params?>
    <?php $useDefList = (\Joomla\Component\Codex\Site\Helper\DateHelper::options($params)[0]
        || $params->get('show_hits') || $params->get('show_category') || $params->get('show_parent_category') || $params->get('show_author') || $assocParam); ?>

    <?php if ($useDefList && !in_array($listStyle, ['simple', 'standard', 'nickel'], true)) : ?>
        <?php echo LayoutHelper::render('codex.content.info_block', ['item' => $this->item, 'params' => $params, 'position' => 'above'], JPATH_COMPONENT . '/layouts'); ?>
    <?php endif; ?>
    <?php if ($params->get('show_tags', 1) && !empty($this->item->tags->itemTags)) : ?>
        <?php echo LayoutHelper::render('posttags', $this->item->tags->itemTags, JPATH_COMPONENT . '/layouts'); ?>
    <?php elseif ($listStyle === 'card' && $params->get('show_tags', 1)) : ?>
        <ul class="tags list-inline invisible" aria-hidden="true"><li class="list-inline-item"><span class="btn btn-sm btn-info">&nbsp;</span></li></ul>
    <?php endif; ?>

    <?php // Content is generated by content plugin event "onContentBeforeDisplay"?>
    <?php echo $this->item->event->beforeDisplayContent; ?>

    <?php echo $this->item->summary; ?>

    <?php if ($params->get('show_readmore') && $this->item->readmore) :
        if ($params->get('access-view')) :
            $link = Route::_(RouteHelper::getPostRoute($this->item->slug, $this->item->catid, $this->item->language));
        else :
            $menu = Factory::getApplication()->getMenu();
            $active = $menu->getActive();
            $itemId = $active->id;
            $link = new Uri(Route::_('index.php?option=com_users&view=login&Itemid=' . $itemId, false));
            $link->setVar('return', base64_encode(RouteHelper::getPostRoute($this->item->slug, $this->item->catid, $this->item->language)));
        endif; ?>

        <?php echo LayoutHelper::render('codex.content.readmore', ['item' => $this->item, 'params' => $params, 'link' => $link]); ?>

    <?php endif; ?>

    <?php if (in_array($listStyle, ['card', 'simple', 'standard', 'nickel'], true)) : ?><div class="mt-auto pt-2"><?php endif; ?>
    <?php if ($listStyle === 'simple') : ?>
        <?php if (\Joomla\Component\Codex\Site\Helper\DateHelper::value($this->item, $params)) : ?>
            <div class="small text-muted"><span class="fa-solid fa-calendar me-1" aria-hidden="true"></span><?php echo \Joomla\Component\Codex\Site\Helper\DateHelper::render($this->item, $params); ?></div>
        <?php endif; ?>
    <?php else : ?>
    <?php echo LayoutHelper::render($listStyle === 'compact' ? 'post.basic-meta' : 'post.meta', $this->item, JPATH_COMPONENT . '/layouts'); ?>
    <?php endif; ?>
    <?php if ($listStyle === 'card') {
        echo LayoutHelper::render('post.card-footer', $this->item, JPATH_COMPONENT . '/layouts');
    } ?>
    <?php if (in_array($listStyle, ['card', 'simple', 'standard', 'nickel'], true)) : ?></div><?php endif; ?>

    <?php if ($isUnpublished) : ?>
        </div>
    <?php endif; ?>

</div>

<?php // Content is generated by content plugin event "onContentAfterDisplay"?>
<?php echo $this->item->event->afterDisplayContent; ?>
<?php endif; ?>

<?php if ($listStyle === 'nickel') : ?><footer class="card-footer"><?php echo LayoutHelper::render('post.basic-meta', $this->item, JPATH_COMPONENT . '/layouts'); ?></footer><?php endif; ?>
</div>
