<?php defined('_JEXEC') or die;use Joomla\CMS\HTML\HTMLHelper;use Joomla\CMS\Router\Route;?>
<form action="<?php echo Route::_('index.php?option=com_codex&task=import.database');?>" method="post" class="card card-body mb-4">
<h2>Move existing content into Posts</h2>
<p>Copy content directly from an installed Joomla extension. The source records are not deleted, and every completed import can be rolled back.</p>
<label class="form-label" for="database-source">Source</label>
<select class="form-select mb-3" id="database-source" name="source" required>
<option value="">Select an installed source</option>
<?php foreach($this->databaseSources as $key=>$source):?><option value="<?php echo htmlspecialchars($key,ENT_QUOTES,'UTF-8');?>"><?php echo htmlspecialchars($source['label'],ENT_QUOTES,'UTF-8');?> (<?php echo (int)$source['count'];?> items)</option><?php endforeach;?>
</select>
<label class="form-label" for="database-category">Fallback destination category</label>
<select class="form-select mb-3" id="database-category" name="catid" required><option value="">Select a category</option><?php foreach($this->categories as $category):?><option value="<?php echo (int)$category->id;?>"><?php echo str_repeat('— ',max(0,(int)$category->level-1)).htmlspecialchars($category->title,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select>
<div class="row g-3 mb-3"><div class="col-md-6"><label class="form-label">Imported post status</label><select class="form-select" name="state"><option value="source">Use source status</option><option value="1">Published</option><option value="0">Unpublished</option><option value="2">Archived</option><option value="-2">Trashed</option></select></div><div class="col-md-6"><label class="form-label">When an alias already exists</label><select class="form-select" name="duplicates"><option value="skip">Skip duplicate</option><option value="copy">Create another post</option></select></div></div>
<label class="form-check mb-3"><input class="form-check-input" type="checkbox" name="download_media" value="1"><span class="form-check-label">Download remote post images into Joomla Media (maximum 10 MB each)</span></label>
<div class="d-flex gap-2"><button class="btn btn-secondary" type="submit" name="preview" value="1">Preview migration</button><button class="btn btn-primary" type="submit">Import into Posts</button></div><?php echo HTMLHelper::_('form.token');?></form>
<form action="<?php echo Route::_('index.php?option=com_codex&task=import.run');?>" method="post" enctype="multipart/form-data" class="card card-body"><h2>Import posts</h2><p>Upload a WordPress WXR/XML export or one or more Markdown files. Preview parses and checks the files without changing the database.</p><label class="form-label">Files</label><input class="form-control mb-3" type="file" name="files[]" accept=".xml,.wxr,.md,.markdown,text/xml,text/markdown" multiple required><label class="form-label">Destination category</label><select class="form-select mb-3" name="catid" required><option value="">Select a category</option><?php foreach($this->categories as $category):?><option value="<?php echo (int)$category->id;?>"><?php echo str_repeat('— ',max(0,(int)$category->level-1)).htmlspecialchars($category->title,ENT_QUOTES,'UTF-8');?></option><?php endforeach;?></select><label class="form-label">Imported post status</label><select class="form-select mb-3" name="state"><option value="source">Use source status</option><option value="1">Published</option><option value="0">Draft</option><option value="-3">Pending</option></select><label class="form-label">When an alias already exists</label><select class="form-select mb-3" name="duplicates"><option value="skip">Skip duplicate</option><option value="copy">Create another post</option></select><label class="form-check mb-3"><input class="form-check-input" type="checkbox" name="download_media" value="1"><span class="form-check-label">Download remote post images into Joomla Media (maximum 10 MB each)</span></label><div class="d-flex gap-2"><button class="btn btn-secondary" type="submit" name="preview" value="1">Preview import</button><button class="btn btn-primary" type="submit">Import now</button></div><?php echo HTMLHelper::_('form.token');?></form>
<?php if($this->batches):?><div class="card mt-4"><div class="card-header"><strong>Recent import batches</strong></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Batch</th><th>Source</th><th>Imported</th><th>Date</th><th></th></tr></thead><tbody><?php foreach($this->batches as $batch):?><tr><td>#<?php echo (int)$batch->id;?></td><td><?php echo htmlspecialchars($batch->source,ENT_QUOTES,'UTF-8');?></td><td><?php echo (int)$batch->imported_count;?></td><td><?php echo htmlspecialchars($batch->created,ENT_QUOTES,'UTF-8');?></td><td><form action="<?php echo Route::_('index.php?option=com_codex&task=import.rollback');?>" method="post" onsubmit="return confirm('Delete all posts created by this import batch?')"><input type="hidden" name="batch_id" value="<?php echo (int)$batch->id;?>"><button class="btn btn-sm btn-danger">Rollback</button><?php echo HTMLHelper::_('form.token');?></form></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;?>
